name: Build and Deploy Songa User Interface
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List file
        run: ls /home/runner/work/Songa/Songa/

      - name: Print working directory
        run: pwd        

      - name: Add known hosts
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Remove previous files
        run: sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} rm -rf /var/www/songa.ui/*
        
      - name: Copy folder contents recursively
        run: sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -r /home/runner/work/Songa/Songa/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/songa.ui/

      - name: Install dependencies
        run: sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} cd /var/www/songa.ui/ && npm install

      - name: Build application
        run: sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} cd /var/www/songa.ui/ && npm run build

